export const referenceModels = [
  {
    id: "cover-hero",
    name: "Cover hero",
    structure: ["full image", "title block", "short proof", "save CTA"],
    variables: ["image", "hook", "proof", "cta"],
    layout: "hero",
    style: { background: "photo", accent: "white", density: "editorial" },
    source: "TikTok collection Carrousel-template-cf",
    editable: true,
  },
  {
    id: "split-proof",
    name: "Split proof",
    structure: ["claim", "image proof", "takeaway"],
    variables: ["claim", "image", "takeaway"],
    layout: "split",
    style: { background: "warm-white", accent: "green", density: "editorial" },
    source: "TikTok collection Carrousel-template-cf",
    editable: true,
  },
  {
    id: "numbered-stack",
    name: "Numbered stack",
    structure: ["hook", "numbered tips", "micro CTA"],
    variables: ["topic", "tips", "cta"],
    layout: "numbered",
    style: { background: "cream", accent: "sage", density: "list" },
    source: "TikTok collection Carrousel-template-cf",
    editable: true,
  },
  {
    id: "checklist-grid",
    name: "Checklist grid",
    structure: ["problem", "checklist", "correction"],
    variables: ["problem", "items", "correction"],
    layout: "checklist",
    style: { background: "white", accent: "terracotta", density: "list" },
    source: "TikTok collection Carrousel-template-cf",
    editable: true,
  },
  {
    id: "before-after",
    name: "Before / after",
    structure: ["before", "switch", "after", "next step"],
    variables: ["before_label", "after_label", "visuals", "cta"],
    layout: "compare",
    style: { background: "white", accent: "green", density: "editorial" },
    source: "TikTok collection Carrousel-template-cf",
    editable: true,
  },
  {
    id: "quote-pause",
    name: "Quote pause",
    structure: ["statement", "pause slide", "reflection"],
    variables: ["quote", "reflection", "cta"],
    layout: "quote",
    style: { background: "charcoal", accent: "cream", density: "minimal" },
    source: "TikTok collection Carrousel-template-cf",
    editable: true,
  },
  {
    id: "routine-cards",
    name: "Routine cards",
    structure: ["routine hook", "time blocks", "habit stack"],
    variables: ["routine_name", "steps", "time", "category"],
    layout: "cards",
    style: { background: "pale-blue", accent: "blue", density: "list" },
    source: "TikTok collection Carrousel-template-cf",
    editable: true,
  },
  {
    id: "myth-fact",
    name: "Myth / fact",
    structure: ["myth", "fact", "why", "action"],
    variables: ["myth", "fact", "explanation", "cta"],
    layout: "myth",
    style: { background: "cream", accent: "plum", density: "editorial" },
    source: "TikTok collection Carrousel-template-cf",
    editable: true,
  },
  {
    id: "mistake-fix",
    name: "Mistake fix",
    structure: ["mistake", "consequence", "fix"],
    variables: ["mistake", "consequence", "fix", "cta"],
    layout: "fix",
    style: { background: "white", accent: "amber", density: "editorial" },
    source: "TikTok collection Carrousel-template-cf",
    editable: true,
  },
  {
    id: "challenge-days",
    name: "Challenge days",
    structure: ["promise", "day cards", "progress CTA"],
    variables: ["challenge_name", "day_number", "action", "progress"],
    layout: "challenge",
    style: { background: "soft-pink", accent: "plum", density: "list" },
    source: "TikTok collection Carrousel-template-cf",
    editable: true,
  },
  {
    id: "symptom-map",
    name: "Symptom map",
    structure: ["signs", "meaning", "reframe"],
    variables: ["problem", "symptoms", "reframe"],
    layout: "bubbles",
    style: { background: "cream", accent: "green", density: "list" },
    source: "TikTok collection Carrousel-template-cf",
    editable: true,
  },
  {
    id: "recipe-flow",
    name: "Recipe flow",
    structure: ["result", "ingredients", "steps", "serving"],
    variables: ["recipe", "ingredients", "steps", "serving"],
    layout: "recipe",
    style: { background: "white", accent: "terracotta", density: "list" },
    source: "TikTok collection Carrousel-template-cf",
    editable: true,
  },
];
