const groups = {
  "Hormones & cortisol": [
    "Things I started doing to support my hormone health",
    "‘Cortisol face’ is all over TikTok—but here’s what you’re missing",
    "Things I wish someone told me about hormones at 20",
    "Hormone health habits that are actually just good lifestyle habits",
    "My realistic hormone-friendly morning routine",
    "5 everyday habits that support a more balanced routine",
    "The realistic version of a ‘low cortisol’ lifestyle",
    "The cortisol habits I stopped romanticizing",
    "Things that help me feel more balanced",
  ],
  "Stress & calm": [
    "How I stopped feeling stressed all the time",
    "5 habits that made me feel calmer",
    "Things I do when I feel overwhelmed",
    "My low-stress morning routine",
    "How I reset after a stressful day",
    "Habits that helped my stress",
    "Things I stopped doing for my stress",
    "Simple habits for calmer mornings",
    "My 10-minute reset routine",
    "Habits that protect my peace",
  ],
  "Overstimulation & reset": [
    "Things I do when I feel overstimulated",
    "You’re not lazy—you might just be overstimulated",
    "My 5pm reset instead of doomscrolling",
    "My reset routine after work",
    "Things I do when I can’t switch my brain off",
    "What I do instead of doomscrolling",
    "Things I stopped doing because my brain felt fried",
    "My low-stimulation morning routine",
    "How I stopped checking my phone first thing",
    "Signs my routine was way too overstimulating",
    "My everything shower reset",
    "My get-my-life-together routine",
    "Things I do when I feel off",
  ],
  "Morning & night": [
    "What my mornings looked like when I was constantly stressed vs now",
    "Things I thought were helping my stress but actually made my mornings worse",
    "My night routine for better days",
    "My clean-girl routine",
    "Things I stopped doing before bed",
    "My realistic 9pm routine",
    "How I stopped waking up exhausted",
    "Habits that helped me sleep better",
    "My night routine after a stressful day",
  ],
  "Energy & food": [
    "How I stopped feeling constantly tired",
    "Why I felt tired even after sleeping",
    "Habits that helped me stop crashing at 3pm",
    "Things I do when I have zero energy",
    "How I stopped feeling tired all day",
    "What I eat when I want steady energy",
    "Things I changed about my coffee routine",
    "My realistic wellness grocery list",
    "Breakfasts that actually keep me full",
    "What I eat on low-energy days",
  ],
  "Glow-up & feminine": [
    "How to glow up in 66 days",
    "How to glow up in 10 weeks",
    "How to glow up in 2 months",
    "Habits that made me feel feminine again",
    "Things I do to feel put together again",
    "My low-effort feel-pretty-again routine",
    "Simple habits that made me glow up",
    "How I started looking more alive",
    "My glow-up habits",
    "Things I stopped doing and looked better",
    "My realistic glow-up routine",
  ],
  "Productivity & boundaries": [
    "Things I stopped saying yes to",
    "Things I stopped explaining to people",
    "How I stay productive without burning out",
    "My realistic productive morning",
    "Things I do when my to-do list feels impossible",
    "How I get things done without stressing myself out",
  ],
  "Fitness & wellness": [
    "My realistic wellness routine",
    "Habits that made me feel better",
    "Why I started walking every day",
    "My low-stress workout routine",
    "Things I do instead of forcing myself to the gym",
    "My realistic Pilates routine",
    "My lazy-girl wellness routine",
    "Small habits that made me feel better",
    "Habits I wish I started sooner",
    "Things I wish I knew earlier",
  ],
  "Weekly & seasonal reset": [
    "My weekly reset checklist",
    "My Sunday reset routine",
    "Things I do every Sunday",
    "My fall reset routine",
  ],
};

export const hookCategories = ["All", ...Object.keys(groups)];
export const hookLibrary = Object.entries(groups).flatMap(([category, hooks]) =>
  hooks.map((text, index) => ({ id: `${category.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-${index + 1}`, category, text })),
);
