"use client";
// Carousel Studio v2: canonical layer editor for production carousels.
import { useEffect,useMemo,useRef,useState } from "react";
import "./editor.css";
import { canonicalLayoutFor } from "../../lib/canonical-layout";
import { getSlideGeometry } from "../../lib/layout-geometry.js";
type Frame={x:number;y:number;width:number;height:number;cropX?:number;cropY?:number;zoom?:number;fit?:string};
type Override={headline?:string;body?:string;assetIds?:Array<string|number>;text?:Record<string,any>;image?:Record<string,any>;imageSlots?:Frame[]};
type Asset={id:string|number;public_url:string;filename:string;source_type?:string;persona_id?:string|null};
const FONTS=["TikTok Sans","Instrument Sans","Manrope","Inter Tight","DM Sans","Plus Jakarta Sans","Space Grotesk","Bricolage Grotesque","Archivo","Urbanist"];
function defaultSlots(layout:string,isHook:boolean,count:number):Frame[]{
 if(layout==="lifestyle-3stack"&&!isHook)return [{x:0,y:0,width:1080,height:450},{x:0,y:450,width:1080,height:450},{x:0,y:900,width:1080,height:450}];
 if(layout==="three-rect-educational")return isHook?[{x:690,y:90,width:300,height:390},{x:90,y:830,width:300,height:390}]:[{x:80,y:110,width:450,height:430},{x:90,y:820,width:390,height:390},{x:600,y:820,width:390,height:390}];
 if(layout==="editorial-asym-hero")return [{x:60,y:190,width:590,height:770},{x:690,y:215,width:310,height:310},{x:690,y:555,width:310,height:310}];
 if(layout==="editorial-collage")return isHook?[{x:42,y:70,width:570,height:760},{x:610,y:210,width:420,height:600}]:[{x:50,y:70,width:500,height:700},{x:560,y:150,width:470,height:620}];
 if(layout==="grid-2x2"&&!isHook)return [{x:32,y:32,width:500,height:635},{x:548,y:32,width:500,height:635},{x:32,y:683,width:500,height:635},{x:548,y:683,width:500,height:635}];
 if(layout==="ranking")return isHook?[{x:70,y:650,width:450,height:420},{x:560,y:650,width:450,height:420}]:[{x:330,y:900,width:420,height:300}];
 return Array.from({length:Math.max(1,count)},()=>({x:0,y:0,width:1080,height:1350}));
}
export default function Editor({params}:{params:Promise<{id:string}>}){
 const [id,setId]=useState(""),[carousel,setCarousel]=useState<any>(),[slides,setSlides]=useState<any[]>([]),[assets,setAssets]=useState<Asset[]>([]),[personas,setPersonas]=useState<any[]>([]),[refs,setRefs]=useState<any[]>([]);
 const [active,setActive]=useState(0),[selection,setSelection]=useState<"headline"|"body"|number>("headline"),[overrides,setOverrides]=useState<Record<string,Override>>({}),[history,setHistory]=useState<Record<string,Override>[]>([]),[future,setFuture]=useState<Record<string,Override>[]>([]);
 const [dirty,setDirty]=useState(false),[busy,setBusy]=useState(""),[scene,setScene]=useState(""),[assetSearch,setAssetSearch]=useState(""),[canvasScale,setCanvasScale]=useState(.5),drag=useRef<any>(null),canvasRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{params.then(x=>setId(x.id))},[params]);
 useEffect(()=>{if(!id)return;Promise.all([fetch("/api/carousels/"+id,{cache:"no-store"}).then(r=>r.json()),fetch("/api/assets",{cache:"no-store"}).then(r=>r.json()),fetch("/api/personas",{cache:"no-store"}).then(r=>r.json()),fetch("/api/visual-references",{cache:"no-store"}).then(r=>r.json())]).then(([c,a,p,v])=>{setCarousel(c.carousel);setSlides(c.slides||[]);setAssets(a.previews||[]);setPersonas(p.personas||[]);setRefs(v.references||[]);setOverrides(c.carousel?.spec?.editor_overrides||{})})},[id]);
 useEffect(()=>{if(!carousel)return;const el=canvasRef.current;if(!el)return;const sync=()=>setCanvasScale(el.getBoundingClientRect().width/1080||.5);sync();const observer=new ResizeObserver(sync);observer.observe(el);return()=>observer.disconnect()},[carousel]);
 const generated=carousel?.spec?.generated_slides||[],slide=slides[active]||{},gen=generated[active]||{},key=String(gen.position||slide.position||active+1),ov=overrides[key]||{},layout=canonicalLayoutFor(carousel?.content_type||carousel?.spec?.carousel_type,carousel?.spec?.model_id||slide.template_id||"single-image"),isHook=active===0||String(gen.role||"").toUpperCase()==="HOOK";
 const isRoutineCtaFinal=layout==="routine-timeline"&&active===generated.length-1&&["CTA","TAKEAWAY"].includes(String(gen.role||"").toUpperCase());
 const isVisualFinal=active===generated.length-1&&(layout!=="routine-timeline"||isRoutineCtaFinal);
 const canonicalGeometry=getSlideGeometry({...gen,layout},isHook,isVisualFinal,{});
 const storedGeometry=slide.render_metadata?.geometry;
 const storedIsCanonical=storedGeometry&&!slide.render_metadata?.synthesized_from_spec&&String(slide.template_id||"")===layout;
 const baseText=(storedIsCanonical?storedGeometry?.text:canonicalGeometry?.text)||{},text={...baseText,...(ov.text||{})},headline=ov.headline??gen.headline??slide.headline??"",body=ov.body??gen.body??slide.body??"";
 const originalIds=(slide.render_metadata?.asset_ids||[slide.asset_id]).filter(Boolean),assetIds=ov.assetIds||originalIds,slots=ov.imageSlots||defaultSlots(layout,isHook,assetIds.length);
 const slotAssets=assetIds.map((aid:any)=>assets.find(a=>String(a.id)===String(aid)));
 const selectedSlot=typeof selection==="number"?selection:null,selectedFrame=selectedSlot===null?null:(slots[selectedSlot]||defaultSlots(layout,isHook,assetIds.length)[selectedSlot]);
 function checkpoint(){setHistory(h=>[...h.slice(-49),structuredClone(overrides)]);setFuture([])}
 function setOv(next:Override,live=false){if(!live)checkpoint();setOverrides(o=>({...o,[key]:{...(o[key]||{}),...next}}));setDirty(true)}
 function textPatch(next:any,live=false){setOv({text:{...(ov.text||{}),...next}},live)}
 function slotPatch(index:number,next:Partial<Frame>,live=false){const arr=slots.map(x=>({...x}));arr[index]={...arr[index]!,...next};setOv({imageSlots:arr},live)}
 function chooseAsset(index:number,aid:string|number){const ids=[...assetIds];ids[index]=aid;setOv({assetIds:ids})}
 function undo(){if(!history.length)return;const prev=history.at(-1)!;setFuture(f=>[structuredClone(overrides),...f]);setOverrides(prev);setHistory(h=>h.slice(0,-1));setDirty(true)}
 function redo(){if(!future.length)return;const next=future[0]!;setHistory(h=>[...h,structuredClone(overrides)]);setOverrides(next);setFuture(f=>f.slice(1));setDirty(true)}
 function down(e:React.PointerEvent,kind:string){e.stopPropagation();checkpoint();const fr=typeof selection==="number"?slots[selection]:null;const textX=selection==="headline"?(text.headlineX??text.x??90):(text.bodyX??text.x??90);drag.current={kind,x:e.clientX,y:e.clientY,x0:fr?.x??Number(textX),y0:fr?.y??Number(selection==="headline"?(text.headlineY??text.y??700):(text.bodyY??900)),w0:fr?.width??Number(text.width||850),h0:fr?.height??300,size0:Number(selection==="headline"?text.headlineSize||54:text.bodySize||28)};(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId)}
 function move(e:React.PointerEvent){const d=drag.current;if(!d)return;const scale=Math.max(.1,canvasScale),dx=(e.clientX-d.x)/scale,dy=(e.clientY-d.y)/scale;if(typeof selection==="number"){if(d.kind==="resize")slotPatch(selection,{width:Math.max(80,Math.round(d.w0+dx)),height:Math.max(80,Math.round(d.h0+dy))},true);else slotPatch(selection,{x:Math.round(d.x0+dx),y:Math.round(d.y0+dy)},true)}else if(d.kind==="resize"){textPatch(selection==="headline"?{width:Math.max(120,Math.round(d.w0+dx)),headlineSize:Math.max(12,Math.round(d.size0+dy*.18))}:{width:Math.max(120,Math.round(d.w0+dx)),bodySize:Math.max(12,Math.round(d.size0+dy*.18))},true)}else textPatch(selection==="headline"?{headlineX:Math.round(d.x0+dx),headlineY:Math.round(d.y0+dy)}:{bodyX:Math.round(d.x0+dx),bodyY:Math.round(d.y0+dy)},true)}
 async function refreshCarousel(){const next=await fetch("/api/carousels/"+id,{cache:"no-store"}).then(r=>r.json());if(next.carousel){setCarousel(next.carousel);setSlides(next.slides||[])}return next}
 async function waitForRender(){for(let attempt=0;attempt<30;attempt+=1){await new Promise(resolve=>setTimeout(resolve,1500));const next=await refreshCarousel();if(next.carousel?.status==="READY_FOR_REVIEW")return true}return false}
 async function save(render=false){setBusy(render?"Rendering…":"Saving…");const spec={...carousel.spec,editor_overrides:overrides};const r=await fetch("/api/carousels/"+id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({spec})});if(!r.ok){setBusy("Save failed");return}setCarousel((c:any)=>({...c,spec}));setDirty(false);if(!render){setBusy("Saved");return}const rr=await fetch("/api/carousels/"+id+"/render",{method:"POST"});if(!rr.ok){setBusy("Render failed");return}if(rr.status===202){setBusy("Render queued…");setBusy(await waitForRender()?"Rendered":"Render still running")}else{await refreshCarousel();setBusy("Rendered")}}
 async function generate(){if(selectedSlot===null)return;const persona=personas.find(p=>p.id===carousel.persona_id)||personas[0],ref=refs[0];if(!persona?.master||!ref){setBusy("Missing persona/reference");return}setBusy("Generating persona image…");const cr=await fetch("/api/image-generation/jobs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({persona_id:persona.id,master_asset_id:persona.master.id,visual_reference_id:ref.id,carousel_id:id,slide_id:"slide_"+key,category:"self_care",scene:scene||"natural candid lifestyle photo matching the selected carousel image slot",framing:"portrait"})});const cj=await cr.json();if(!cj.job?.id){setBusy(cj.error||"Generation failed");return}const rr=await fetch("/api/image-generation/jobs/"+cj.job.id,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"run"})});const out=await rr.json();if(out.asset?.id){setAssets(a=>[out.asset,...a]);chooseAsset(selectedSlot,out.asset.id);setBusy("Generated & inserted")}else setBusy(out.error||"Generation failed")}
 if(!carousel)return <main className="ce-loading">Loading Carousel Studio…</main>;
 const filtered=assets.filter(a=>!assetSearch||[a.filename,a.source_type,a.persona_id].join(" ").toLowerCase().includes(assetSearch.toLowerCase())).slice(0,160);
 return <main className="ce-shell" tabIndex={-1} onKeyDown={e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?redo():undo()}}}>
  <header className="ce-top"><a href="/">← Carrousels</a><strong>Carousel Studio · {carousel.content_type}</strong><button disabled={!history.length} onClick={undo}>↶</button><button disabled={!future.length} onClick={redo}>↷</button><span>{dirty?"Unsaved":"Saved"}</span><button onClick={()=>save()}>Save</button><button className="primary" onClick={()=>save(true)}>Save & render</button></header>
  <aside className="ce-slides">{generated.map((s:any,i:number)=><button key={s.position} className={i===active?"active":""} onClick={()=>{setActive(i);setSelection("headline")}}><span>{s.position}</span><img src={slides[i]?.rendered_url||carousel.spec?.rendered_slides?.[i]?.url||""}/></button>)}</aside>
  <section className="ce-work"><div ref={canvasRef} className={"ce-canvas layout-"+layout}>
   {layout==="interactive-checklist"&&!isHook&&<div className="ce-checklist-panel"/>}
   {layout==="ranking"&&<div className="ce-ranking-wash"/>}
   {slotAssets.map((asset:Asset|undefined,i:number)=>asset&&<div key={i} className={"ce-image-frame "+(selection===i?"sel":"")} style={{left:slots[i]!.x*canvasScale,top:slots[i]!.y*canvasScale,width:slots[i]!.width*canvasScale,height:slots[i]!.height*canvasScale}} onClick={()=>setSelection(i)} onPointerDown={e=>{setSelection(i);down(e,"move")}} onPointerMove={move} onPointerUp={()=>drag.current=null}><img draggable={false} src={asset.public_url} style={{transform:`scale(${slots[i]!.zoom||1})`,objectPosition:`${slots[i]!.cropX??50}% ${slots[i]!.cropY??50}%`}}/>{selection===i&&<i className="ce-handle" onPointerDown={e=>down(e,"resize")} onPointerMove={move}/>}</div>)}
   <div className={"ce-text "+(selection==="headline"?"sel":"")} onClick={()=>setSelection("headline")} onPointerDown={e=>down(e,"move")} onPointerMove={move} onPointerUp={()=>drag.current=null} style={{left:Number(text.headlineX??text.x??90)*canvasScale,top:Number(text.headlineY??text.y??700)*canvasScale,width:Number(text.width||850)*canvasScale,fontSize:Number(text.headlineSize||54)*canvasScale,color:text.editorHeadlineColor||text.headlineColor||"#fff",fontFamily:text.fontFamily||"TikTok Sans",textAlign:text.align||"left",fontWeight:text.headlineWeight||700}}>{headline}{selection==="headline"&&<i className="ce-handle" onPointerDown={e=>down(e,"resize")} onPointerMove={move}/>}</div>
   {body&&<div className={"ce-text body "+(selection==="body"?"sel":"")} onClick={()=>setSelection("body")} onPointerDown={e=>down(e,"move")} onPointerMove={move} onPointerUp={()=>drag.current=null} style={{left:Number(text.bodyX??text.x??90)*canvasScale,top:Number(text.bodyY||900)*canvasScale,width:Number(text.width||850)*canvasScale,fontSize:Number(text.bodySize||28)*canvasScale,color:text.editorBodyColor||text.bodyColor||"#fff",fontFamily:text.fontFamily||"TikTok Sans",textAlign:text.align||"left",fontWeight:text.bodyWeight||500}}>{body}{selection==="body"&&<i className="ce-handle" onPointerDown={e=>down(e,"resize")} onPointerMove={move}/>}</div>}
  </div><div className="ce-status">{busy}</div></section>
  <aside className="ce-props"><div className="ce-layerlist"><b>Layers</b><button className={selection==="headline"?"active":""} onClick={()=>setSelection("headline")}>T · Title</button>{body&&<button className={selection==="body"?"active":""} onClick={()=>setSelection("body")}>T · Body</button>}{slots.map((_,i)=><button className={selection===i?"active":""} key={i} onClick={()=>setSelection(i)}>▧ · Image {i+1}</button>)}</div>
   {typeof selection!=="number"?<div className="ce-panel"><label>Text<textarea value={selection==="headline"?headline:body} onChange={e=>setOv(selection==="headline"?{headline:e.target.value}:{body:e.target.value})}/></label><label>Font<select value={text.fontFamily||"TikTok Sans"} onChange={e=>textPatch({fontFamily:e.target.value})}>{FONTS.map(x=><option key={x}>{x}</option>)}</select></label><div className="ce-row"><label>Size<input type="number" value={selection==="headline"?text.headlineSize||54:text.bodySize||28} onChange={e=>textPatch(selection==="headline"?{headlineSize:+e.target.value}:{bodySize:+e.target.value})}/></label><label>Color<input type="color" value={(selection==="headline"?text.editorHeadlineColor||text.headlineColor:text.editorBodyColor||text.bodyColor)||"#ffffff"} onChange={e=>textPatch(selection==="headline"?{editorHeadlineColor:e.target.value,headlineColor:e.target.value}:{editorBodyColor:e.target.value,bodyColor:e.target.value})}/></label></div><label>Align<select value={text.align||"left"} onChange={e=>textPatch({align:e.target.value})}><option>left</option><option>center</option><option>right</option></select></label><div className="ce-row"><label>X<input type="number" value={selection==="headline"?(text.headlineX??text.x??90):(text.bodyX??text.x??90)} onChange={e=>textPatch(selection==="headline"?{headlineX:+e.target.value}:{bodyX:+e.target.value})}/></label><label>Y<input type="number" value={selection==="headline"?(text.headlineY??text.y??700):(text.bodyY??900)} onChange={e=>textPatch(selection==="headline"?{headlineY:+e.target.value}:{bodyY:+e.target.value})}/></label></div><div className="ce-row"><label>Width<input type="number" value={text.width??850} onChange={e=>textPatch({width:+e.target.value})}/></label><label>Weight<input type="number" min="100" max="900" step="100" value={selection==="headline"?text.headlineWeight||700:text.bodyWeight||500} onChange={e=>textPatch(selection==="headline"?{headlineWeight:+e.target.value}:{bodyWeight:+e.target.value})}/></label></div></div>:
   <div className="ce-panel"><h3>Image {selection+1}</h3><div className="ce-row"><label>X<input type="number" value={selectedFrame?.x||0} onChange={e=>slotPatch(selection,{x:+e.target.value})}/></label><label>Y<input type="number" value={selectedFrame?.y||0} onChange={e=>slotPatch(selection,{y:+e.target.value})}/></label></div><div className="ce-row"><label>Width<input type="number" value={selectedFrame?.width||0} onChange={e=>slotPatch(selection,{width:+e.target.value})}/></label><label>Height<input type="number" value={selectedFrame?.height||0} onChange={e=>slotPatch(selection,{height:+e.target.value})}/></label></div><label>Zoom<input type="range" min="1" max="4" step=".05" value={selectedFrame?.zoom||1} onChange={e=>slotPatch(selection,{zoom:+e.target.value})}/></label><div className="ce-row"><label>Crop X<input type="range" min="0" max="100" value={selectedFrame?.cropX??50} onChange={e=>slotPatch(selection,{cropX:+e.target.value})}/></label><label>Crop Y<input type="range" min="0" max="100" value={selectedFrame?.cropY??50} onChange={e=>slotPatch(selection,{cropY:+e.target.value})}/></label></div><h3>Replace</h3><input placeholder="Search assets…" value={assetSearch} onChange={e=>setAssetSearch(e.target.value)}/><div className="ce-assets">{filtered.map(a=><button key={a.id} title={a.filename} onClick={()=>chooseAsset(selection,a.id)}><img src={a.public_url}/></button>)}</div><h3>Generate with {personas.find(p=>p.id===carousel.persona_id)?.name||carousel.persona_id}</h3><textarea value={scene} onChange={e=>setScene(e.target.value)} placeholder="Scene: mirror selfie after skincare…"/><button className="primary wide" onClick={generate}>Generate & insert here</button></div>}
   <button className="reset" onClick={()=>{checkpoint();setOverrides(o=>{const n={...o};delete n[key];return n});setDirty(true)}}>Reset slide to template</button>
  </aside>
 </main>
}