export const contentFormats = [
  { id: 'C01_ROUTINE', description: 'A realistic sequence of small routine steps', required_inputs: ['topic', 'goal'], optional_inputs: ['season', 'items'], recommended_slide_count: 7, recommended_templates: ['T01_FULLSCREEN_HOOK', 'T04_ROUTINE', 'T07_CTA'], recommended_asset_mix: ['persona', 'stock'], cta_behavior: 'soft' },
  { id: 'C02_CHECKLIST', description: 'A saveable practical checklist', required_inputs: ['topic'], optional_inputs: ['items', 'goal'], recommended_slide_count: 7, recommended_templates: ['T01_FULLSCREEN_HOOK', 'T03_CHECKLIST', 'T07_CTA'], recommended_asset_mix: ['persona', 'stock'], cta_behavior: 'save' },
  { id: 'C03_THINGS_I_STOPPED', description: 'Relatable things stopped', required_inputs: ['topic'], optional_inputs: ['audience'], recommended_slide_count: 7, recommended_templates: ['T01_FULLSCREEN_HOOK', 'T02_PHOTO_TEXT', 'T07_CTA'], recommended_asset_mix: ['persona'], cta_behavior: 'soft' },
  { id: 'C04_THINGS_I_STARTED', description: 'Relatable things started', required_inputs: ['topic'], optional_inputs: ['goal'], recommended_slide_count: 7, recommended_templates: ['T01_FULLSCREEN_HOOK', 'T02_PHOTO_TEXT', 'T07_CTA'], recommended_asset_mix: ['persona'], cta_behavior: 'soft' },
  { id: 'C05_GLOW_UP', description: 'Lifestyle glow-up habits without medical claims', required_inputs: ['topic'], optional_inputs: ['season'], recommended_slide_count: 7, recommended_templates: ['T01_FULLSCREEN_HOOK', 'T04_ROUTINE', 'T07_CTA'], recommended_asset_mix: ['persona', 'stock'], cta_behavior: 'soft' },
  { id: 'C06_POV_RELATABLE', description: 'A short POV story', required_inputs: ['topic', 'angle'], optional_inputs: [], recommended_slide_count: 6, recommended_templates: ['T01_FULLSCREEN_HOOK', 'T06_STORY', 'T07_CTA'], recommended_asset_mix: ['persona'], cta_behavior: 'comment' },
  { id: 'C07_MISTAKES', description: 'Common routine mistakes framed as personal experience', required_inputs: ['topic'], optional_inputs: ['goal'], recommended_slide_count: 7, recommended_templates: ['T01_FULLSCREEN_HOOK', 'T02_PHOTO_TEXT', 'T07_CTA'], recommended_asset_mix: ['persona'], cta_behavior: 'soft' },
  { id: 'C08_MY_REALISTIC', description: 'A realistic day or routine', required_inputs: ['topic'], optional_inputs: ['items'], recommended_slide_count: 7, recommended_templates: ['T01_FULLSCREEN_HOOK', 'T04_ROUTINE', 'T07_CTA'], recommended_asset_mix: ['persona'], cta_behavior: 'soft' },
  { id: 'C09_LIST', description: 'A list of useful lifestyle ideas', required_inputs: ['topic'], optional_inputs: ['items'], recommended_slide_count: 7, recommended_templates: ['T01_FULLSCREEN_HOOK', 'T03_CHECKLIST', 'T07_CTA'], recommended_asset_mix: ['persona', 'stock'], cta_behavior: 'save' },
  { id: 'C10_BEFORE_AFTER', description: 'A non-medical personal before/after habit contrast', required_inputs: ['topic'], optional_inputs: ['goal'], recommended_slide_count: 7, recommended_templates: ['T01_FULLSCREEN_HOOK', 'T02_PHOTO_TEXT', 'T07_CTA'], recommended_asset_mix: ['persona'], cta_behavior: 'soft' }
] as const;
