export const contentFormats = [
  { id: 'F01_LIFESTYLE_GUIDE', description: 'Organic lifestyle advice led by a human persona', concepts: ['STARTED_STOPPED','GLOW_UP','THINGS_CHANGED'], min_slides: 5, max_slides: 8, copy_voice: 'personal/confessional', visual_mode: 'single-image', structure: 'persona fullscreen hook -> context -> habits -> felt result -> soft CortiFree -> CTA' },
  { id: 'F02_EDITORIAL_COLLAGE', description: 'Pinterest/editorial glow-up storytelling in a fixed asymmetric hero collage', concepts: ['GLOW_UP','BEAUTY_WELLNESS_HACKS'], min_slides: 5, max_slides: 7, copy_voice: 'editorial/aspirational', visual_mode: 'editorial-asym-hero', structure: 'sparse editorial cover -> 1 large left hero + 2 stacked right supports on every slide -> concise practice + benefit -> CortiFree/recap' },
  { id: 'F03_ROUTINE_TIMELINE', description: 'Chronological routine people can copy', concepts: ['MORNING_ROUTINE','NIGHT_ROUTINE','DAY_IN_LIFE'], min_slides: 6, max_slides: 8, copy_voice: 'minimal/chronological', visual_mode: 'routine-timeline', structure: 'title + time range hook -> one timed action per slide -> takeaway/CTA' },
  { id: 'F04_AESTHETIC_EDUCATIONAL', description: 'Soft educational content with a fixed three-rectangle image composition', concepts: ['EDUCATIONAL_HOW_TO','THINGS_CHANGED','GLOW_UP'], min_slides: 5, max_slides: 8, copy_voice: 'educational/simple', visual_mode: 'three-rect-educational', structure: 'top-left headline + exactly 3 supporting rectangles + centered concise explanation -> takeaway/CTA' },
  { id: 'F05_INTERACTIVE_CHECKLIST', description: 'Interactive self-audit with programmatic checkbox rows', concepts: ['INTERACTIVE_CHECKLIST','EDUCATIONAL_HOW_TO'], min_slides: 5, max_slides: 8, copy_voice: 'interactive/second-person', visual_mode: 'interactive-checklist', structure: 'contextual photo + low cover panel -> one concrete question + 2-4 checkbox choices per body slide -> takeaway/CTA' },
  { id: 'F06_PERSONA_EXPLAINER', description: 'Human-led relatable explanation', concepts: ['SIGNS_WHY','BEFORE_AFTER','EDUCATIONAL_HOW_TO'], min_slides: 5, max_slides: 8, copy_voice: 'relatable/explanatory', visual_mode: 'persona-explainer', structure: 'fullscreen persona hook -> new persona photo + mini headline + 2-4 observations per slide -> soft CTA' },
  { id: 'F07_RANKING', description: 'Editorial rating format with a fixed score block and one item per slide', concepts: ['RANKING_RATING','BEAUTY_WELLNESS_HACKS','THINGS_CHANGED'], min_slides: 5, max_slides: 9, copy_voice: 'opinionated/ranking', visual_mode: 'ranking', structure: 'short cover + exactly 2 teasers -> one left-side item photo + programmatic X/10 or tier score + short reason -> recap/CTA' },
  { id: 'F08_2X2', description: 'Existing diagonal 2-image contrast renderer', concepts: ['BEFORE_AFTER','STARTED_STOPPED','EDUCATIONAL_HOW_TO','SIGNS_WHY'], min_slides: 5, max_slides: 8, copy_voice: 'contrast/punchy', visual_mode: 'grid-2x2', structure: 'existing 2x2 hook/body behavior with exactly 2 unique images repeated diagonally' },
] as const;
