export const contentFormats = [
  { id: 'F01_LIFESTYLE_GUIDE', description: 'Organic lifestyle advice led by a human persona', concepts: ['STARTED_STOPPED','GLOW_UP','THINGS_CHANGED'], min_slides: 5, max_slides: 8, copy_voice: 'personal/confessional', visual_mode: 'single-image', structure: 'persona fullscreen hook -> context -> habits -> felt result -> soft CortiFree -> CTA' },
  { id: 'F02_EDITORIAL_COLLAGE', description: 'Pinterest/editorial glow-up storytelling in a fixed asymmetric hero collage', concepts: ['GLOW_UP','BEAUTY_WELLNESS_HACKS'], min_slides: 5, max_slides: 7, copy_voice: 'editorial/aspirational', visual_mode: 'editorial-asym-hero', structure: 'sparse editorial cover -> 1 large left hero + 2 stacked right supports on every slide -> concise practice + benefit -> CortiFree/recap' },
  { id: 'F03_ROUTINE_TIMELINE', description: 'Photo-first day-in-the-life / morning / night routine', concepts: ['MORNING_ROUTINE','NIGHT_ROUTINE','DAY_IN_LIFE'], min_slides: 6, max_slides: 8, copy_voice: 'minimal/diary-like', visual_mode: 'routine-timeline', structure: 'centered hero routine cover + overall time range -> one compact start-end time + action block on each full-screen photo -> final routine step by default; soft CTA optional' },
  { id: 'F04_AESTHETIC_EDUCATIONAL', description: 'Structured beauty/wellness educational checklist board with concise, saveable copy', concepts: ['EDUCATIONAL_HOW_TO','THINGS_CHANGED','GLOW_UP'], min_slides: 5, max_slides: 8, copy_voice: 'educational/checklist', visual_mode: 'three-rect-educational', structure: 'light 2-image diagonal title cover -> body: top-left proof image + top-right labeled 3-5 bullet checklist + short centered subject title + 2 bottom support visuals' },
  { id: 'F05_INTERACTIVE_CHECKLIST', description: 'Interactive self-audit with programmatic checkbox rows', concepts: ['INTERACTIVE_CHECKLIST','EDUCATIONAL_HOW_TO'], min_slides: 5, max_slides: 8, copy_voice: 'interactive/second-person', visual_mode: 'interactive-checklist', structure: 'contextual photo + low cover panel -> one concrete question + 2-4 checkbox choices per body slide -> takeaway/CTA' },
  { id: 'F06_PERSONA_EXPLAINER', description: 'Human-led relatable explanation', concepts: ['SIGNS_WHY','BEFORE_AFTER','EDUCATIONAL_HOW_TO'], min_slides: 5, max_slides: 8, copy_voice: 'relatable/explanatory', visual_mode: 'persona-explainer', structure: 'fullscreen persona hook -> new persona photo + mini headline + 2-4 observations per slide -> soft CTA' },
  { id: 'F07_RANKING', description: 'Girly editorial tier list inspired by native TikTok ranking carousels', concepts: ['RANKING_RATING','BEAUTY_WELLNESS_HACKS','THINGS_CHANGED'], min_slides: 7, max_slides: 9, copy_voice: 'opinionated/tier-list', visual_mode: 'ranking', structure: 'clean title cover + exactly 2 teaser images -> one F/D/C/B/A/S/SS+ tier per slide with item title + 2-3 concise opinionated lines + optional 0-2 support images -> saveable outro' },
  { id: 'F08_2X2', description: 'Existing diagonal 2-image contrast renderer', concepts: ['BEFORE_AFTER','STARTED_STOPPED','EDUCATIONAL_HOW_TO','SIGNS_WHY'], min_slides: 5, max_slides: 8, copy_voice: 'contrast/punchy', visual_mode: 'grid-2x2', structure: 'existing 2x2 hook/body behavior with exactly 2 unique images repeated diagonally' },
  { id: 'F09_LIFESTYLE_3STACK', description: 'Native lifestyle carousel with three stacked candid images per advice slide', concepts: ['BEAUTY_WELLNESS_HACKS','THINGS_CHANGED','MORNING_ROUTINE','NIGHT_ROUTINE','GLOW_UP'], min_slides: 6, max_slides: 9, copy_voice: 'casual/lifestyle', visual_mode: 'lifestyle-3stack', structure: 'fullscreen lifestyle cover with short hook -> exactly 3 edge-to-edge horizontal lifestyle images per body slide + one compact advice block over the middle image -> final saveable lifestyle takeaway' },
] as const;
